### ISSUE TITLE
Ugly list item / padding problem with Gnome 3.18

### ISSUE THREAD

**Issue by Saren-Arterius** [snwh/paper-gtk-theme#228]
The list items on left are really ugly.
![Really ugly](https://na.cx/i/YM6fu0.png)

**Comment by dejl** [comment]
same here on Gnome 3.18

**Comment by KillianKemps** [comment]
+1 Same problem here with Gnome 3.18

**Comment by stefanmaric** [comment]
+1 Same problem after gnome upgrade to 3.18

**Comment by kimamb** [comment]
+1

**Comment by MissingNoIOI** [comment]
+1

**Comment by Screwtapello** [comment]
Looks like this was fixed in 8c8c5691, so if you download the latest version of the Paper theme it should Just Work.

**Comment by kimamb** [comment]
It was not fixed

**Comment by gfavaro** [comment]
+1

**Comment by vega231** [comment]
still not fixed (Gnome Shell 3.18.2) tried multiple themes, only Adwaita and Numix seems to be ok)
![screenshot from 2016-02-13 12-06-54](https://cloud.githubusercontent.com/assets/16963624/13027320/573e58e0-d24a-11e5-8769-ce356ba91994.png)
